### ISSUE TITLE
[EPIC]: add usage and coverage for Frictionless Airdrop (HIP-904)

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#1012]
### Problem
HIP-904, *Frictionless Airdrop*, has been fully implemented in `services@0.56.1` but currently lacks Solidity usage and test coverage.

### Solution
Implement Solidity usage and add test coverage to verify that all features function as expected.

```[tasklist]
### HIP 904 System Contract Function Verification Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1171
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1170
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1101
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1102
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1160
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1109
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1147
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1188
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1189
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1190
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1191
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1208
```
Note: As of 0.56 the target of an airdrop should be an EOA. Also MN does not yet support this logic

**Comment by Nana-EC** [comment]
@quiet-node or @victor-yanev let's clean up https://github.com/hashgraph/hedera-smart-contracts/pull/1011 and get it in now.
May also need to do a positive handoff to another team member to handle this depending on how sprint planning goes.
Whoever picks this up should sync w @stoyanov-st for context on latest 0.57 functionality as there may be new gaps.

**Comment by Nana-EC** [comment]
@quiet-node added that we should upgrade the local node version of the repo to support this and ensure the feature flag is turned on.

**Comment by quiet-node** [comment]
Refer to PR #1011 on GitHub for a valuable reference.

**Comment by simzzz** [comment]
I'm picking this up, you can assign me

**Comment by quiet-node** [comment]
This design document serves as an additional valuable reference:https://github.com/hashgraph/hedera-services/blob/v0.56.1/hedera-node/docs/design/services/smart-contract-service/frictionless-airdrops-system-contracts.md
