### ISSUE TITLE
[EPIC] ERC Registry 

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#1028]
### Problem

On Hedera both HTS tokens and ERC tokens are supported. However, HTS tokens have improved APIs and allow for easy retrieval of existence and balance across accounts on the network. 
Like other EVM chains, it is not easy to know what all ERC tokens are specified within smart contracts on the network without first knowing the contracts and confirming they accurately implement the interface needed.
With this in mind it's difficult for the mirror node explorer or other apps to know and display ERCs

### Solution
Implement a new project to create a registry of contracts that are highly likely to be ERCs. The Mirror node explorer and other applications can use this list as a foundation to enhance their user experience.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1066
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1067
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1107
```

**Comment by Nana-EC** [comment]
@quiet-node and @natanasow to sync up on this and product a design doc first highlight approach. 
Doc should be placed in `tools/erc-repository-indexer/docs/registry_design.md`

**Comment by Nana-EC** [comment]
Suggestion from @acuarica to utilize the verification service to add additional confidence.
This could be done using the verification service APIs

**Comment by david-bakin-sl** [comment]
Discussions about this Epic at https://github.com/hashgraph/hedera-smart-contracts/discussions/1035

**Comment by Nana-EC** [comment]
@quiet-node can we close this? If not open items please go ahead and close
