### ISSUE TITLE
[EPIC] LZ <> HTS Exploration

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#1030]
### Problem

LZ is deployed on Hedera and we'd like to dig into see what's possible when considering HTS and it's representation fo ERC20 and ERC 721s

### Solution

https://limechain.notion.site/Layer-Zero-Hedera-15a10baa8dcd8020a77edd60f41816c7?pvs=73

Explore the LZ offering, gain familiarity as a team and POC so cross chain bridging of HTS tokens (or discover any issues

```[tasklist]
### Tasks
- [x] - https://github.com/hashgraph/hedera-smart-contracts/issues/1047
- [x] - https://github.com/hashgraph/hedera-smart-contracts/issues/1051
- [x] - https://github.com/hashgraph/hedera-smart-contracts/issues/1052
- [x] - https://github.com/hashgraph/hedera-smart-contracts/issues/1060
- [x] - https://github.com/hashgraph/hedera-smart-contracts/issues/1077
- [x] - https://github.com/hashgraph/hedera-smart-contracts/issues/1078
- [x] - https://github.com/hashgraph/hedera-smart-contracts/issues/1079
- [x] - https://github.com/hashgraph/hedera-smart-contracts/issues/1080
- [x] - https://github.com/hashgraph/hedera-smart-contracts/issues/1061
- [x] - https://github.com/hashgraph/hedera-smart-contracts/issues/1062
- [x] - Document how to wrap a fungible HTS token in LZ ecosystem for the community
- [x] - Document how to wrap a non-fungible HTS token in LZ ecosystem for the community
```

Additional content 
- [[Ethereum Mainnet](https://etherscan.io/token/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2)](https://etherscan.io/token/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2)
- [[Arbitrum](https://arbiscan.io/token/0x82af49447d8a07e3bd95bd0d56f35241523fbab1)](https://arbiscan.io/token/0x82af49447d8a07e3bd95bd0d56f35241523fbab1)
- [[Optimism](https://optimistic.etherscan.io/token/0x4200000000000000000000000000000000000006)](https://optimistic.etherscan.io/token/0x4200000000000000000000000000000000000006)
- [[MaticWETH](https://polygonscan.com/token/0x7ceb23fd6bc0add59e62ac25578270cff1b9f619#code)](https://polygonscan.com/token/0x7ceb23fd6bc0add59e62ac25578270cff1b9f619#code)
- [[Base](https://basescan.org/token/0x4200000000000000000000000000000000000006)](https://basescan.org/token/0x4200000000000000000000000000000000000006)
- https://docs.layerzero.network/v2
- https://docs.layerzero.network/v2/developers/evm/create-lz-oapp/start
- https://docs.layerzero.network/v2/developers/evm/developer-overview
- [OApp](https://docs.layerzero.network/v2/developers/evm/oapp/overview)
- [OFT](https://docs.layerzero.network/v2/developers/evm/oft/quickstart)
- [ONFT](https://docs.layerzero.network/v2/developers/evm/onft/quickstart)
- [LZ EVM Contracts](https://github.com/LayerZero-Labs/LayerZero-v2/tree/main/packages/layerzero-v2/evm)

**Comment by Nana-EC** [comment]
@natanasow I think we can close this right?
Most of the issues were resolved in the last PR and I think the current PR should be complete today
