### ISSUE TITLE
[EPIC]: Add usage and coverage for Hedera Account Service (HAS) System Contract (HIP-632)

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#1037]
### Problem

HIP 632 has been fully implemented in 0.57 but currently lacks complete Solidity usage and test coverage.

### Solution

Implement Solidity usage and add test coverage to verify that all features function as expected.

```[tasklist]
### HIP 632 System Contract Function Verification Tasks
- [ ] upgrade the local node version of the repo to support HIP-632 and ensure the feature flag is turned on (should be on by default).
- [ ] Add an IHRC632.sol that captures getEvmAddressAlias(address), getHederaAccountNumAlias(address) and isValidAlias(address), isAuthorized and isAuthorizedRaw functions to IHederaAccountService.sol
- [ ] Add an IHRC904Proxy.sol that captures isAuthorized and isAuthorizedRaw
- [ ] Add tests that verify IHRC632 for queries
- [ ] Add tests that verify IHRC632 for state changing transactions
```

**Comment by Nana-EC** [comment]
@quiet-node and @david-bakin-sl are we still waiting on services fixes or did these go into 0.58?
If so this can be complete in 0.59.0 B.
If not and it's in 0.59 then this ticket should be pushed out one more sprint to be done in 0.60.0 A
