### ISSUE TITLE
[ERC Registry EPIC] Phase 1: Develop and implement a tool for indexing the Hedera network to detect ERC-20 and ERC-721 contracts.

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#1066]
### Problem
The ERC Registry is an initiative aimed at creating a comprehensive registry of contracts that are widely recognized and believed to be standard ERC token contracts with a high degree of confidence. At this early phase of the project, it requires a design document to highlight and outline the approach.

### Solution
As a first pass to accelerate improved UX we can produce a registry of contracts that are beleived with high confidence to be  ERC's. The Mirror node explorer and other apps can take this list as a starting point to build out their UX for users.

Simple approach is to
- create a self contained runnable npm project `erc-repository-indexer` under `tools`. 
- Index the networks contracts and verify they are ERC20 or ERC721 by matching the presence of interface function bytes. Utilize current POC on 1st pass if applicable and then [sevm](https://github.com/acuarica/evm) soon after. Ensure the tool support the specification of `env`, mirrorNodeUrl` and `startingContractId` to allow for flexibility. 
- Create an ERC20s_<env>.json and an ERC721s_<evn>.json file each with the appropriate but minimal details. Files should be placed under `tools/erc-repository-indexer/registry`. Entries should be sorted in ascending order of contractId
- For additional confidence one may simulate an `eth_call` on the functions also. Consider pros and cons based on accuracy to this point
- Make the tool runnable in CI with the output being a new PR with the file updates for approval and merge 

A starting schema for an ERC20 may be
```json
{
    "address": "0x....",  // Address of the ERC20 contract/token
    "contractId": "0.0.x",  // contract id of the ERC20 contract/token
  }
```

A starting schema for an ERC721 may be
```json
{
    "address": "0x....",  // Address of the ERC20 contract/token
    "contractId": "0.0.x",  // contract id of the ERC20 contract/token
  }
```

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1029
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1036
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1038
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1039
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1040
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1041
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1056
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1042

```
