### ISSUE TITLE
[ERC Registry EPIC] Phase 2: Integrate validation through the contract call API and address edge cases to enhance accuracy.

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#1067]
### Problem  
After [Phase 1](https://github.com/hashgraph/hedera-smart-contracts/issues/1066), the  ERC indexing tool can now detect ERC contracts and categorize them into ERC-20 and ERC-721. However, the categorized contracts only include the contract ID and EVM address, lacking other essential information such as name, symbol, and decimals.

### Solution  
Implement a new mechanism to make calls to the mirror node to retrieve the necessary information.

A better and improved schema for an ERC20 should include detailed token information
```json
{
    "address": "0x....",  // Address of the ERC20 contract/token
    "contractId": "0.0.x",  // contract id of the ERC20 contract/token
    "name": "...",
    "symbol": "...",
    "decimals": x,
    "totalSupply": "..."
  }
```

A better and improved schema for an ERC721 should include detailed token information
```json
{
    "address": "0x....",  // Address of the ERC20 contract/token
    "contractId": "0.0.x",  // contract id of the ERC20 contract/token
    "name": "...",
    "symbol": "...",
  }
```

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1059
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1070
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1065
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1074
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1081
```
