### ISSUE TITLE
[ERC Registry EPIC] Phase 3: Further features

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#1107]
### Problem  
Currently, the ERC Registry project has an MVP capable of indexing the network, detecting ERC-20 and ERC-721 tokens, and writing the records to the registry. However, additional features could enhance the tool and make it more versatile.  

### Solution  
Implement new enhancements and features based on user feedback to improve the tool.  

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1111
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1128
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1131
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1133
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1130
- [x] ~~[ERC Registry] Phase 3: Add functionality for bytecode storage.~~
```

**Comment by quiet-node** [comment]
The proposed functionality to store bytecode in the registry may not be practical to implement, as it does not provide additional benefits and could negatively impact performance. Bytecodes are typically large, and the registry contains thousands of contracts. Including bytecode for each contract would significantly increase the size of the registry files, resulting in longer load times for dependent applications. Given these drawbacks, this feature will be temporarily removed from the roadmap.
