### ISSUE TITLE
[ERC Registry] Phase 3: address team feedback on the first MVP

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#1111]
### Problem  
Currently, the ERC Registry project has an MVP capable of indexing the network, detecting ERC-20 and ERC-721 tokens, and writing the records to the registry. The team is currently evaluating the project and feedback is coming in.

### Solution  
Address team feedback

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1112
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1114
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/1118
```
