### ISSUE TITLE
[EPIC] npm publish repo

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#115]
### Problem

Currently we've versioned the repo however other consumers of the system contract functions are forced to copy contracts and compile themselves.
This results in inconsistency of the details of the contracts and adds extra work on the consumers

### Solution

Publish npm versions of the repo along with releases.

Create an `@hashgrph.hedera/smart-contracts` npm package that includes the smart contracts under `/contracts`. Not only interfaces and base wrapper examples should be included. All non interfaces should include an `/examples` path to ensure it's clear these contracts are examples

We should also support deployment of alpha releases.

```[tasklist]
### Tasks
- [ ] Review repo to confirm layout is suitable for publishing
- [ ] Move contracts to improve structure
- [ ] Deploy alpha/beta vesion to confirm consumption
```

**Comment by acuarica** [comment]
In addition to publish the `npm` package, we should explore how Foundry users can consume the precompile functions.

Foundry uses git submodules to consume dependencies https://book.getfoundry.sh/projects/dependencies.

As an example, solmate https://github.com/transmissions11/solmate allows both Hardhat and Foundry users to consume their contracts.

**Comment by Nana-EC** [comment]
We should have separate packages for
- https://github.com/hashgraph/hedera-smart-contracts/tree/main/contracts/system-contracts (should include ABI files)
- https://github.com/hashgraph/hedera-smart-contracts/tree/main/system-contract-dapp-playground

This will allow for other repos to more easily consume the contracts e.g. foundry example as noted above by @acuarica

**Comment by Nana-EC** [comment]
Potential approach

- 1st - system contract interfaces only i.e. IHederaTokenService, IHRC719 etc
- 2nd - low level wrapping contracts -  once we've had some keen eyes on it to give us comfort e.g. https://github.com/hashgraph/hedera-smart-contracts/blob/main/contracts/system-contracts/hedera-token-service/examples/hrc-719/HRC719Contract.sol
- 3rd - Test/example contracts for complex flows - likely under a different path or package name to make a clear separation
