### ISSUE TITLE
Explore ERC support

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#203]
### Problem

The Smart Contract service has E2E support for multiple ERC's given the EVM equivalence protocol journey and RPC support.
We should capture which all

### Solution

Explore [ERCs](https://eips.ethereum.org/erc) w examples or references
- [x] [EIP 20](https://eips.ethereum.org/EIPS/eip-20)
- [x] [EIP 721](https://eips.ethereum.org/EIPS/eip-721)
- [x] [EIP 777](https://eips.ethereum.org/EIPS/eip-777)
- [x] [EIP 1155](https://eips.ethereum.org/EIPS/eip-1155)

Where possible we should add examples utilizing ERCs, HTS or other system contract or at the least provide a link to OZ examples to show coverage.

These should be broken out into separate tickets addressing the ask

**Comment by quiet-node** [comment]
Close as done
