### ISSUE TITLE
Explore OZ 4.x coverage

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#204]
### Problem

OZ provides many useful templates that smart contract devs are used to utilizing.
However, it may not be clear what coverage the Hedera Smart Contract Service 2.0 has for them

### Solution

Provide test example of OZ module support.
For each module create a contract, test the methods and add to a list of OZ modules covered.
Core module should be added to CI

Interfaces
- [x] [IERC20](https://docs.openzeppelin.com/contracts/4.x/api/token/ERC20#IERC20)
- [ ] [IERC20Metadata](https://docs.openzeppelin.com/contracts/4.x/api/token/ERC20#IERC20Metadata)
- [x] [IERC165](https://docs.openzeppelin.com/contracts/4.x/api/utils#IERC165)
- [x] [IERC721](https://docs.openzeppelin.com/contracts/4.x/api/token/ERC721#IERC721)
- [x] [IERC721Receiver](https://docs.openzeppelin.com/contracts/4.x/api/token/ERC721#IERC721Receiver)
- [ ] [IERC721Enumerable](https://docs.openzeppelin.com/contracts/4.x/api/token/ERC721#IERC721Enumerable)
- [ ] [IERC721Metadata](https://docs.openzeppelin.com/contracts/4.x/api/token/ERC721#IERC721Metadata)
- [x] [IERC777](https://docs.openzeppelin.com/contracts/4.x/api/token/ERC777#IERC777)
- [x] [IERC777Recipient](https://docs.openzeppelin.com/contracts/4.x/api/token/ERC777#IERC777Recipient)
- [x] [IERC777Sender](https://docs.openzeppelin.com/contracts/4.x/api/token/ERC777#IERC777Sender)
- [x] [IERC1155](https://docs.openzeppelin.com/contracts/4.x/api/token/ERC1155#IERC1155)
- [ ] [IERC1155Receiver](https://docs.openzeppelin.com/contracts/4.x/api/token/ERC1155#IERC1155Receiver)
- [ ] [IERC1155MetadataURI](https://docs.openzeppelin.com/contracts/4.x/api/token/ERC1155#IERC1155MetadataURI)
- [ ] [IERC1271](https://docs.openzeppelin.com/contracts/4.x/api/interfaces#IERC1271)
- [ ] [IERC1363](https://docs.openzeppelin.com/contracts/4.x/api/interfaces#IERC1363)
- [ ] [IERC1820Implementer](https://docs.openzeppelin.com/contracts/4.x/api/utils#IERC1820Implementer)
- [ ] [IERC1820Registry](https://docs.openzeppelin.com/contracts/4.x/api/utils#IERC1820Registry)
- [ ] [IERC1822Proxiable](https://docs.openzeppelin.com/contracts/4.x/api/interfaces#IERC1822Proxiable)
- [ ] [IERC2612](https://docs.openzeppelin.com/contracts/4.x/api/interfaces#IERC2612)
- [ ] [IERC2981](https://docs.openzeppelin.com/contracts/4.x/api/interfaces#IERC2981)
- [ ] [IERC3156FlashLender](https://docs.openzeppelin.com/contracts/4.x/api/interfaces#IERC3156FlashLender)
- [ ] [IERC3156FlashBorrower](https://docs.openzeppelin.com/contracts/4.x/api/interfaces#IERC3156FlashBorrower)
- [x] [IERC4626](https://docs.openzeppelin.com/contracts/4.x/api/interfaces#IERC4626)

Concepts/libraries
- [ ] [access](https://docs.openzeppelin.com/contracts/4.x/api/access)
- [ ] [paymentsplitter](https://docs.openzeppelin.com/contracts/4.x/api/finance)
- [ ] [vestingwallet](https://docs.openzeppelin.com/contracts/4.x/api/finance)
- [ ] [governor](https://docs.openzeppelin.com/contracts/4.x/api/governance)
- [ ] [meta](https://docs.openzeppelin.com/contracts/4.x/api/metatx)
- [ ] [proxy](https://docs.openzeppelin.com/contracts/4.x/api/proxy)
- [ ] [pullpayment](https://docs.openzeppelin.com/contracts/4.x/api/security)
- [ ] [reentrancyguade](https://docs.openzeppelin.com/contracts/4.x/api/security)
- [ ] [pausable](https://docs.openzeppelin.com/contracts/4.x/api/security)
- [ ] [math](https://docs.openzeppelin.com/contracts/4.x/api/utils)
- [ ] [cryptography](https://docs.openzeppelin.com/contracts/4.x/api/utils)
- [ ] [escrow](https://docs.openzeppelin.com/contracts/4.x/api/utils)
- [ ] [introspection](https://docs.openzeppelin.com/contracts/4.x/api/utils)
- [ ] [crosschain](https://docs.openzeppelin.com/contracts/4.x/api/crosschain)

**Comment by quiet-node** [comment]
Close as done
