### ISSUE TITLE
Add user support to run mixture of automation test suites

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#229]
### Problem

The repo has a good wealth of test automation for smart contratc scenarios.
Most of this is run in Github actions and it may not be clear to users how to run individual tests and the whole test suite in various combinations.

### Solution

Add full test suite documentation and command line run scenarios.

- [ ] Add a README under https://github.com/hashgraph/hedera-smart-contracts/tree/main/test explaining test layout 
- [ ] Add instructions to run an individual suite - these will likely mimic what github actions do
- [ ] Add instructions to run the whole suite in a simple manner that gives confidence of result
- [ ] Add instructions to point single and full suite test to remote environments i.e. mainnet, testnet and previewnet (not using localnode)
