### ISSUE TITLE
System Contract DApp Playground: Phase 1

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#274]
### Problem

Smart contract development and troubleshooting can be time consuming.
A sample and reference DApp to make it easy to test Hedera System Contract would be very useful

### Solution

System Contract DApp Playground: Phase 1
```[tasklist]
### System Contract DApp Playground: Phase 1
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/275
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/276
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/277
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/278
```
