### ISSUE TITLE
System Contract DApp Playground: Phase 2

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#279]
### Problem

Smart contract development and troubleshooting can be time consuming.
A sample and reference DApp to make it easy to test Hedera System Contract would be very useful

### Solution

Add support to the DApp to deploy all the system contracts
```[tasklist]
### System Contract DApp Playground: Phase 2
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/281
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/280
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/291
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/295
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/302
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/303
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/304
```
