### ISSUE TITLE
System Contract DApp Playground: Phase 3

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#314]
### Problem

In [phase 2](https://github.com/hashgraph/hedera-smart-contracts/issues/279), the DApp has successfully achieved the capability to deploy the smart contracts. Phase 3's primary emphasis will shift towards refining contract interactions. This requires making the methods of the smart contracts accessible within the DApp Playground.

### Solution

Incorporate essential Solidity methods, UI components, contract-interacting APIs, and develop unit tests tailored for each individual smart contract.

```[tasklist]
### System Contract DApp Playground: Phase 3
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/316
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/322
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/321
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/319
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/318
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/317
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/315
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/340
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/368
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/371
```
