### ISSUE TITLE
[System Contract DApp - ERC20] Add contract interacting APIs and Unit Tests

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#326]
### Problem

The ERC20Contract requires a set of APIs to interact with contract on chain

### Solution

- Develop APIs to interact with methods from TokenCreateCustom contract
- Create unit tests to verify the accuracy of the contract's APIs.

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/330
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/332
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/333
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/335
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/336
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/337
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/338
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/339
```
