### ISSUE TITLE
[Smart Contract DApp] Phase 4 - Automation

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#390]
### Problem

[Smart Contract DApp] Phase 4 - Automation

### Solution

[Smart Contract DApp] Phase 4 - Automation

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/307
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/388
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/389
```
