### ISSUE TITLE
[System Contract DApp] Future features

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#399]
### Problem

A list of future features that would be nice to have for the dapp.

### Solution

Add more components to fulfill the requirements in the task list

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/400
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/401
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/405
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/420
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/421
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/427
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/434
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/658
```
