### ISSUE TITLE
Solidity Equivalence Support 

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#429]
### Problem

The Hedera network supports solidity as one of the smart contracts development languages.
Occasionally items have shown up that surfaced inequivalence at the language layer.

### Solution

Add exhaustive test support of solidity language features to ensure equivalence.

```[tasklist]
### Solidity Equivalence Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/428
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/430
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/431
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/432
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/441
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/443
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/444
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/445
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/446
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/447
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/448
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/449
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/450
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/459
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/470
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/471
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/472
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/473
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/480
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/482
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/483
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/487
```

**Comment by Nana-EC** [comment]
Nice work team
