### ISSUE TITLE
[Solidity Support] ABI Encoding and Decoding

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#432]
### Problem

The Hedera network supports solidity as one of the smart contracts development languages.
Occasionally items have shown up that surfaced inequivalence at the language layer.

### Solution

- Add a `contracts/solidity/encoding` folder
- Add an `encoding.sol` with test support for encoding and decoding properties as follows

```[tasklist]
### Tasks
- [x] `abi.decode(bytes memory encodedData, (...)) returns (...)`
- [x] `abi.encode(...) returns (bytes memory)`
- [x] `abi.encodePacked(...) returns (bytes memory)`
- [x] `abi.encodeWithSelector(bytes4 selector, ...) returns (bytes memory)`
- [x] `abi.encodeWithSignature(string memory signature, ...) returns (bytes memory)`
- [x] `abi.encodeCall(function functionPointer, (...)) returns (bytes memory)`
```

 Ref: https://docs.soliditylang.org/en/latest/units-and-global-variables.html
