### ISSUE TITLE
[Solidity Support] Official Solidity docs contract example support

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#495]
### Problem

The Hedera network supports solidity as one of the smart contracts development languages.
Occasionally items have shown up that surfaced in-equivalence at the language layer.

### Solution

Implement the example contracts noted on the official solidity documentation

```[tasklist]
### Contract example Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/488
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/489
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/490
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/491
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/492
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/493
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/494
```

**Comment by ebadiere** [comment]
All of the examples are complete and closed.
