### ISSUE TITLE
OZ 5.x Contract Support

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#504]
### Problem

The Hedera network supports smart contracts as part of EVM equivalence.
Occasionally items have shown up that surfaced inequivalence at the language or opcode layer.

OZ provides many useful templates that smart contract devs are used to utilizing.
However, it may not be clear what coverage the Hedera Smart Contract Service 2.0 has for them

### Solution

Provide test example of OZ 5.x contract examples
For each module create a contract under `contracts/oz/<module>` and test the methods in `test/oz/<module>`.
All tickets can find referneces at https://docs.openzeppelin.com/contracts/5.x/

```[tasklist]
### OZ 5.x Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/536
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/538
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/539
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/540
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/596
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/542
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/544
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/545
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/546
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/547
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/554
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/568
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/549
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/552
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/556
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/557
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/564
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/565
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/577
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/613
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/587
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/590
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/599
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/603
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/619
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/625
```

```[tasklist]
### Tasks
```
