### ISSUE TITLE
Solidity Assembly Yul support

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#505]
### Problem

The Hedera network supports smart contracts as part of EVM equivalence.
Occasionally items have shown up that surfaced inequivalence at the language or opcode layer.

Solidity supports inline assembly usage of the Yul language. 
However, it may not be clear what coverage the Hedera Smart Contract Service 2.0 has for them

### Solution

Add solidity contract examples that utilize various syntax options for assembly using Yul
Each ticket should add a contract under `contracts/yul/<grouping>` and tests under similar directories
Ref: https://docs.soliditylang.org/en/latest/yul.html#evm-dialect

```[tasklist]
### Inline assembly Yul Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/518
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/517
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/516
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/515
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/514
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/511
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/519
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/520
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/527
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/530
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/534
```

**Comment by quiet-node** [comment]
closed as finished
