### ISSUE TITLE
[Solidity Assembly Yul support] Contract Caller

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#534]
### Problem

The Hedera network supports smart contracts as part of EVM equivalence.
Occasionally items have shown up that surfaced inequivalence at the language or opcode layer.

Solidity supports inline assembly usage of the Yul language.
However, it may not be clear what coverage the Hedera Smart Contract Service 2.0 has for them

### Solution

- Add solidity contract example that utilize contract call options for assembly using Yul

- Add a contract under contracts/yul/contract-caller and tests under respective directories

Ref: https://docs.soliditylang.org/en/latest/yul.html#evm-dialect

```[tasklist]
### Tasks
- [x] call(g, a, v, in, insize, out, outsize)
- [x] staticcall(g, a, in, insize, out, outsize)
- [x] callcode(g, a, v, in, insize, out, outsize)
- [x] delegatecall(g, a, in, insize, out, outsize)
```
