### ISSUE TITLE
HIP-1010: Updating token custom fees through hts-precompile

### ISSUE THREAD

**Issue by mamorales1** [hashgraph/hedera-smart-contracts#607]
### Problem

Currently, `HederaTokenService` contract doesn't allow users to update token custom fees so if you have created a token with a fee schedule key but you didn't create the token with a custom fee, you will not be able to add custom fees to your token, since `updateTokeInfo` function updates `HederaToken` struct where custom fees are not present. To do so, you only have the choice of using HTS's TokenFeeScheduleUpdateTransaction transaction, but you will not be able to do it through smart contracts.

### Solution

Creating new functions only to update token custom fees.

### Alternatives

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/855
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/874
- [ ] https://github.com/hashgraph/hedera-services/issues/11508
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/876
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/862
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/910
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/915
```

**Comment by Nana-EC** [comment]
Hi  @mamorales1 thanks for the ticket.
Indeed it does seem to be a gap, we'll take a look and circle back here.

**Comment by ebadiere** [comment]
We've confirmed that this is an issue.  We are working on a solution and will let you know when it's on the road map.
