### ISSUE TITLE
Multiple packages need to be upgraded

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#641]
### Problem

At present, the project has outdated main dependencies that need upgrading to the latest version for proper compatibility. This is the cause of the failure of pull request #610.

**Note 1: This upgrade includes updating `@hashgraph/hedera-local` to the latest version, thereby upgrading `ethersjs` from version 5x to 6x. Etherjs 6x introduces more breaking changes compared to version 5x. Consequently, the entire test folder will be updated to align with etherjs@6x. This update will be addressed in [issue#550](https://github.com/hashgraph/hedera-smart-contracts/issues/550).

**Note 2: This upgrade involves updating @openzeppelin/hardhat-upgrades to ensure compatibility with OpenZeppelin's UUPSUpgradable contract and @openzeppelin/contracts-upgradeable version 5x.

### Solution

- Upgrade all dependencies to the latest versions
  - "@hashgraph/hedera-local": "^2.17.2"
  - "@hashgraph/sdk": "^2.40.0"
  - "@nomicfoundation/hardhat-chai-matchers": "^2.0.3"
  - "@openzeppelin/hardhat-upgrades": "^3.0.2"
  - "hardhat": "^2.19.4"
  
- Update the test folder to align with etherjsv6
- Update the usage of UUPSUpgradableV5

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/642
- [x] [Upgrade Ethers to latest version](https://github.com/hashgraph/hedera-smart-contracts/issues/550)
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/643
```
