### ISSUE TITLE
Add sol coverage for 0.8.23

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#682]
### Problem

No contract examples exist to capture the [new features of 0.8.23](https://soliditylang.org/blog/2023/11/08/solidity-0.8.23-release-announcement/)

### Solution

Add an example contract under `/contracts/solidity/versions/0.8.23` that highlights advancements from https://soliditylang.org/blog/2023/11/08/solidity-0.8.23-release-announcement

```[tasklist]
### Tasks
- [x] Update hardhat config
- [x] Update solidity examples to use 0.8.23
- [ ] Add example contract with features noted in 0.8.23 release
```

**Comment by Nana-EC** [comment]
See https://github.com/hashgraph/hedera-smart-contracts/pull/680 feel free to complete or start a new one

**Comment by quiet-node** [comment]
Hello @Nana-EC, following the `Solidity 0.8.23 Release Announcement`, it appears that the release 0.8.23 has only a few of changes, addressing the `invalid verbatim deduplication bug` (which only occurs in pure Yul programs) and introducing two compiler features: `--yul-optimizations` and `optimizerSteps`. With that said, I think the task of `Adding an example contract demonstrating the features highlighted in the 0.8.23 release` may not be required.
