### ISSUE TITLE
Add sol coverage for 0.8.24

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#683]
### Problem

No contract examples exist to capture the [new features of 0.8.24](https://soliditylang.org/blog/2024/01/26/solidity-0.8.24-release-announcement/)

### Solution

Add an example contract under `/contracts/solidity/versions/0.8.24` that highlights advancements from https://soliditylang.org/blog/2024/01/26/solidity-0.8.24-release-announcement/

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-smart-contracts/issues/688
- [ ] Add coverage example for Shard Blob Transactions (EIP-4844) noted in 0.8.24 release
- [ ] Add coverage example for changes in SELFDESTRUCT Behavior (EIP-6780) noted in 0.8.24 release
```

**Comment by quiet-node** [comment]
replaced by https://github.com/hashgraph/hedera-smart-contracts/issues/725
