### ISSUE TITLE
Analyze Hedera EVM Compatibility with the Ethereum Go-client

### ISSUE THREAD

**Issue by se7enarianelabs** [hashgraph/hedera-smart-contracts#788]
### Problem

The goal of this issue is to analyze the Hedera EVM compatibility with the Ethereum Go client: [github.com/ethereum/go-ethereum/ethclient](https://pkg.go.dev/github.com/ethereum/go-ethereum/ethclient). We should test every RPC endpoint (Websockets, HTTP) against this specification: [OpenRPC Specification](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/hashgraph/hedera-json-rpc-relay/main/docs/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false).

As the end result, we should have a separate go-client folder here: [hedera-json-rpc-relay/tools](https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/tools), and the automated tests against the specification should be added to this workflow: [dev-tool-test.yml](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/.github/workflows/dev-tool-test.yml).

### Solution

We have divided the work into a few steps:

- [ ]  Develop the equivalent of the hardhat-example using the Go client.
- [ ]  Develop tests that will test the Go client against the Hedera RPC specification.
- [ ]  Add the tests to the workflow.
- [ ]  Prepare documentation (compatibility report, usage in Hedera, limitations, etc.).
