### ISSUE TITLE
[EPIC] Improve README docs

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#89]
### Problem

The README docs could be improved with diagrams and steps on building and running tests

### Solution

Update the README doc with
- [x] add repo build and test steps
- [ ] add references to system contract function hashes - can use `solc --hashes <file-path>` to calculate
- [ ] architecture overview of code flow i.e. this -> services via calls to address etc

**Comment by Ferparishuertas** [comment]
Outdated
