### ISSUE TITLE
Verify support for solidity versions since 0.8.24

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#993]
### Problem

Solidity support for new solidity versions since 0.8.24 have not been verified.

No contract examples exist to capture the [new features of 0.8.25](https://soliditylang.org/blog/2024/03/14/solidity-0.8.25-release-announcement)

### Solution

Explore contract executions using new versioing compilation and consider adding examples under `/contracts/solidity/versions/0.8.x` for the following versions.
- [ ] [0.8.25](https://soliditylang.org/blog/2024/03/14/solidity-0.8.25-release-announcement)
- [ ] [0.8.26](https://soliditylang.org/blog/2024/05/21/solidity-0.8.26-release-announcement)
- [ ] [0.8.27](https://soliditylang.org/blog/2024/09/04/solidity-0.8.27-release-announcement)
- [ ] [0.8.28](https://soliditylang.org/blog/2024/10/09/solidity-0.8.28-release-announcement)

**Comment by Nana-EC** [comment]
@Ferparishuertas made a good point about looking into how the compiler versions modify the byte code and see how it impacts this story. @acuarica also had inputs here
